name: Fetch Tokens from Moralis with Twitter Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Kiểm tra token và gửi Telegram mỗi 5 phút

jobs:
  fetch-and-post:
    runs-on: ubuntu-latest
    concurrency: fetch-and-post # Giới hạn chỉ 1 workflow chạy cùng lúc
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: node index.js

# Workflow riêng cho kiểm tra và đăng tweet
name: Check and Post to Twitter

on:
  schedule:
    - cron: '*/10 * * * *' # Kiểm tra và đăng tweet mỗi 10 phút
  workflow_dispatch:

jobs:
  check-and-post:
    runs-on: ubuntu-latest
    concurrency: check-and-post # Giới hạn chỉ 1 workflow chạy cùng lúc
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: node index.js --check-twitter # Thêm tham số để chạy chỉ checkAndPostToTwitter