name: Fetch Tokens from Moralis

on:
  schedule:
    - cron: '*/10 * * * *' # Chạy mỗi 30 phút
  workflow_dispatch:

jobs:
  fetch-tokens:
    runs-on: ubuntu-latest
    concurrency: fetch-tokens # Giới hạn chỉ một workflow chạy cùng lúc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Log cron start
        run: echo "Cron job started at $(date -u)"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          echo "Dependencies installed:"
          ls -la node_modules | grep firebase-admin || echo "firebase-admin not found in node_modules"

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MORALIS_API_KEY: ${{ secrets.MORALIS_API_KEY }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node index.js

      - name: Log completion
        run: echo "Cron job completed at $(date -u)"